perf: use inheritance to improve our code base
supabase-community/postgrest-py pull request #47
Opened 2021-12-17 04:50 UTC by leynier

Resolve #40

2021-12-20 02:27 UTC, dreinon requested changes

2021-12-24 19:32 UTC, leynier commented on postgrest_py/base_request_builder.py
> +            "count=(exact|planned|estimated)", session.headers["prefer"]
This header comes from httpx

2021-12-25 07:22 UTC, leynier commented on postgrest_py/__init__.py
> -from postgrest_py.config import DEFAULT_POSTGREST_CLIENT_HEADERS  # noqa: F401
Ok 👍🏼

2021-12-25 07:29 UTC, leynier commented on postgrest_py/base_request_builder.py
> +class BaseSelectRequestBuilder(BaseFilterRequestBuilder):
This pull request does not change the behavior itself. On the other hand, `postgrest-js` allows calling order, then the eq filter, and then order again. So I propose to resolve that issue in another pull request.

2021-12-25 07:52 UTC, J0 approved these changes

2021-12-25 12:53 UTC, dreinon commented on postgrest_py/base_request_builder.py
> +class BaseSelectRequestBuilder(BaseFilterRequestBuilder):
Okay, sure! :+1:

2021-12-25 14:42 UTC, dreinon approved these changes

2021-12-25 17:16 UTC, anand2312 approved these changes
Whoops, I'd looked through this earlier, forgot to approve. LGTM 🚀

2021-12-25 18:30 UTC, lqmanh commented
LGTM

2021-12-25 18:34 UTC, merged

2021-12-28 02:43 UTC, J0 commented
Hey @lqmanh,

Sorry to bother you again but we were hoping to publish a new release with these changes when we realized that we don't quite have access to publish to `postgrest-py` https://pypi.org/project/postgrest-py/ on PyPI. Wondering if you could grant us permissions?

My handle is `joellee` and @dreinon 's handle is `dreinon`

2021-12-28 09:04 UTC, lqmanh commented
@J0 OK I'll grant you permission